# ===== STAGE 1: BUILD =====
FROM node:20-alpine AS build

WORKDIR /app

# Copy package files trước để cache
COPY package*.json ./

RUN npm install

# Copy source
COPY . .

# Build Vite
RUN npm run build


# ===== STAGE 2: SERVE =====
FROM nginx:alpine

# Xóa config mặc định
RUN rm /etc/nginx/conf.d/default.conf

# Copy config nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy build output từ stage build
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
